/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.accounts.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Account service. Represents a row in the &quot;GB_Account&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.accounts.model.impl.AccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.accounts.model.impl.AccountImpl}.
 * </p>
 *
 * @author a616659
 * @see Account
 * @see com.liferay.docs.accounts.model.impl.AccountImpl
 * @see com.liferay.docs.accounts.model.impl.AccountModelImpl
 * @generated
 */
public interface AccountModel extends BaseModel<Account>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account model instance should use the {@link Account} interface instead.
	 */

	/**
	 * Returns the primary key of this account.
	 *
	 * @return the primary key of this account
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account.
	 *
	 * @param primaryKey the primary key of this account
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this account.
	 *
	 * @return the uuid of this account
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this account.
	 *
	 * @param uuid the uuid of this account
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the account ID of this account.
	 *
	 * @return the account ID of this account
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account.
	 *
	 * @param accountId the account ID of this account
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the group ID of this account.
	 *
	 * @return the group ID of this account
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this account.
	 *
	 * @param groupId the group ID of this account
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this account.
	 *
	 * @return the company ID of this account
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account.
	 *
	 * @param companyId the company ID of this account
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account.
	 *
	 * @return the user ID of this account
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this account.
	 *
	 * @param userId the user ID of this account
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account.
	 *
	 * @return the user uuid of this account
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this account.
	 *
	 * @param userUuid the user uuid of this account
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this account.
	 *
	 * @return the user name of this account
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this account.
	 *
	 * @param userName the user name of this account
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this account.
	 *
	 * @return the create date of this account
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account.
	 *
	 * @param createDate the create date of this account
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account.
	 *
	 * @return the modified date of this account
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account.
	 *
	 * @param modifiedDate the modified date of this account
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this account.
	 *
	 * @return the first name of this account
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this account.
	 *
	 * @param firstName the first name of this account
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the family name of this account.
	 *
	 * @return the family name of this account
	 */
	@AutoEscape
	public String getFamilyName();

	/**
	 * Sets the family name of this account.
	 *
	 * @param familyName the family name of this account
	 */
	public void setFamilyName(String familyName);

	/**
	 * Returns the email of this account.
	 *
	 * @return the email of this account
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this account.
	 *
	 * @param email the email of this account
	 */
	public void setEmail(String email);

	/**
	 * Returns the birthday of this account.
	 *
	 * @return the birthday of this account
	 */
	@AutoEscape
	public String getBirthday();

	/**
	 * Sets the birthday of this account.
	 *
	 * @param birthday the birthday of this account
	 */
	public void setBirthday(String birthday);

	/**
	 * Returns the gender of this account.
	 *
	 * @return the gender of this account
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this account.
	 *
	 * @param gender the gender of this account
	 */
	public void setGender(String gender);

	/**
	 * Returns the account password of this account.
	 *
	 * @return the account password of this account
	 */
	@AutoEscape
	public String getAccountPassword();

	/**
	 * Sets the account password of this account.
	 *
	 * @param accountPassword the account password of this account
	 */
	public void setAccountPassword(String accountPassword);

	/**
	 * Returns the marital status of this account.
	 *
	 * @return the marital status of this account
	 */
	@AutoEscape
	public String getMaritalStatus();

	/**
	 * Sets the marital status of this account.
	 *
	 * @param maritalStatus the marital status of this account
	 */
	public void setMaritalStatus(String maritalStatus);

	/**
	 * Returns the interests of this account.
	 *
	 * @return the interests of this account
	 */
	@AutoEscape
	public String getInterests();

	/**
	 * Sets the interests of this account.
	 *
	 * @param interests the interests of this account
	 */
	public void setInterests(String interests);

	/**
	 * Returns the education level of this account.
	 *
	 * @return the education level of this account
	 */
	@AutoEscape
	public String getEducationLevel();

	/**
	 * Sets the education level of this account.
	 *
	 * @param educationLevel the education level of this account
	 */
	public void setEducationLevel(String educationLevel);

	/**
	 * Returns the foreign languages of this account.
	 *
	 * @return the foreign languages of this account
	 */
	@AutoEscape
	public String getForeignLanguages();

	/**
	 * Sets the foreign languages of this account.
	 *
	 * @param foreignLanguages the foreign languages of this account
	 */
	public void setForeignLanguages(String foreignLanguages);

	/**
	 * Returns the profession of this account.
	 *
	 * @return the profession of this account
	 */
	@AutoEscape
	public String getProfession();

	/**
	 * Sets the profession of this account.
	 *
	 * @param profession the profession of this account
	 */
	public void setProfession(String profession);

	/**
	 * Returns the preferences of this account.
	 *
	 * @return the preferences of this account
	 */
	@AutoEscape
	public String getPreferences();

	/**
	 * Sets the preferences of this account.
	 *
	 * @param preferences the preferences of this account
	 */
	public void setPreferences(String preferences);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.docs.accounts.model.Account account);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.docs.accounts.model.Account> toCacheModel();

	@Override
	public com.liferay.docs.accounts.model.Account toEscapedModel();

	@Override
	public com.liferay.docs.accounts.model.Account toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}